In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [2]:
df = pd.read_csv("data/posts.csv")
df.head()

,title,body
0,I was once reading this article that went as: ...,"['#SportsAnalytics', 'Iâ€™m a ManU fan. I want C..."
1,How do you change your setup on Jupyter to loo...,['IMPORT EXCEL DATAFRAME']
2,The reality of 9/10 data scientist job specs!,['It would be Requirements-PhD and 15 years ex...
3,oh fuck ðŸ˜‚ðŸ˜‚ðŸ˜‚this had no business to be funny,"[""God the fact that he didn't even refence ano..."
4,ARtYfIshaL NtEliGeNtS,"['Read this as ""artificial negligence"" and it ..."

In [3]:
df.describe()

                                                    title   body
count                                               12100  12022
unique                                              12100   4679
top     Yeah, but it also can reference getting data p...     []
freq                                                    1   7156

In [4]:
df.dropna()

,title,body
0,I was once reading this article that went as: ...,"['#SportsAnalytics', 'Iâ€™m a ManU fan. I want C..."
1,How do you change your setup on Jupyter to loo...,['IMPORT EXCEL DATAFRAME']
2,The reality of 9/10 data scientist job specs!,['It would be Requirements-PhD and 15 years ex...
3,oh fuck ðŸ˜‚ðŸ˜‚ðŸ˜‚this had no business to be funny,"[""God the fact that he didn't even refence ano..."
4,ARtYfIshaL NtEliGeNtS,"['Read this as ""artificial negligence"" and it ..."
...,...,...
12095,I need to start dropping that into interviews ...,[]
12096,Big assumption to believe a corporation has th...,[]
12097,"honestly true, imma take the class tho i under...",[]
12098,This guy groks.,[]
12099,"Yeah, but it also can reference getting data p...",[]

In [5]:
df = df[df["body"].astype(str) != "[]"]

In [6]:
# remove emojis
df = df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))
df.head()

,title,body
0,I was once reading this article that went as: ...,"['#SportsAnalytics', 'Im a ManU fan. I want Ca..."
1,How do you change your setup on Jupyter to loo...,['IMPORT EXCEL DATAFRAME']
2,The reality of 9/10 data scientist job specs!,['It would be Requirements-PhD and 15 years ex...
3,oh fuck this had no business to be funny,"[""God the fact that he didn't even refence ano..."
4,ARtYfIshaL NtEliGeNtS,"['Read this as ""artificial negligence"" and it ..."

In [10]:
df.dropna()

,title,body
0,I was once reading this article that went as: ...,"['#SportsAnalytics', 'Im a ManU fan. I want Ca..."
1,How do you change your setup on Jupyter to loo...,['IMPORT EXCEL DATAFRAME']
2,The reality of 9/10 data scientist job specs!,['It would be Requirements-PhD and 15 years ex...
3,oh fuck this had no business to be funny,"[""God the fact that he didn't even refence ano..."
4,ARtYfIshaL NtEliGeNtS,"['Read this as ""artificial negligence"" and it ..."
...,...,...
12081,Loll that last sentence is pretty accurate. Ye...,['Good luck man. You might discover you really...
12082,"I wouldn't worry about it, as long as you have...","['Hate these basic ass wranglers.', ""I need to..."
12084,They can be willing but that doesn't make them...,['Big assumption to believe a corporation has ...
12092,This is a cope to rationalize not taking a har...,"['honestly true, imma take the class tho i und..."
12094,Hate these basic ass wranglers.,['[deleted]']

In [11]:
df.to_csv("cleaned_data.csv", index=False)

In [8]:
def clean_data(data):
    if type(data) == float:
        return ""
    # temp = data.lower()
    temp = re.sub("'", "", temp)  # to avoid removing contractions in english
    temp = re.sub("@[A-Za-z0-9_]+", "", temp)  # remove mentions
    temp = re.sub("#[A-Za-z0-9_]+", "", temp)  # remove hashtags
    temp = re.sub(r'http\S+', '', temp)  # remove urls
    temp = re.sub('[()!?]', ' ', temp)  # remove special characters
    temp = re.sub('\[.*?\]', ' ', temp)
    temp = re.sub("[^a-z0-9]", " ", temp) 
    temp = temp.split()
    temp = " ".join(word for word in temp)
    return temp

<>:10: SyntaxWarning: invalid escape sequence '\['
<>:10: SyntaxWarning: invalid escape sequence '\['
/tmp/ipykernel_5498/3634063640.py:10: SyntaxWarning: invalid escape sequence '\['
  temp = re.sub('\[.*?\]', ' ', temp)

In [9]:
df = df[df['body']].apply(clean_data)
df.head()

KeyError: 'None of [Index([\'[\'#SportsAnalytics\', \'Im a ManU fan. I want Cavani to do well. But Im also finishing up my Masters in Data Analytics and this made me laugh out loud. Well done\', \'tbf im pretty sure a linear regression could predict Lewis Hammertime as a 8 time world champion. Should I write an article and call it AI?\']\',\n       \'[\'IMPORT EXCEL DATAFRAME\']\',\n       \'[\'It would be Requirements-PhD and 15 years experience required Job duties: Meme\']\',\n       \'["God the fact that he didn\'t even refence another cell is what gets me. He typed in =1+2", \'Right, this is the last place I expect to see a meme that kills me \']\',\n       \'[\'Read this as "artificial negligence" and it also applies\', \'After learning how to use "if" function \', \'MuHsHeEn LeRnInG\', \'\']\',\n       \'[\'You da best siens\', "I\'m sure we can figure this out with 50% more data and a linear regression!"]\',\n       \'[\'I got paid 6 figures at one point in my career to show people how to connect their Excel workbooks to external data sources.\', \'Nothing like VBA to automate data flows though.\']\',\n       \'[\'Brain successfully melted.\']\', \'[\'Dude, same this is great\']\',\n       \'[\'I think so fuck can anyone link me resources on how to get started in data science? I hear its the sexiest job in the world and I wanna make 200k someone help is this boot camp good?\']\',\n       ...\n       \'[\'For when upper management asks you to work with some cpython spaghetti where a previous employee tried to make their own "more optimized" algorithm or class for keras\', \'Probably just a broad OOP, coulda been C# or Java interchangeably\']\',\n       \'[\'Well, I have\']\', \'[\'What are these\']\',\n       \'["It\'s been a while since I was in undergrad, and my major was physics, so im not sure if that would have prepared me for it differently than others. But yeah, the stuff you\'re talking about came up in LA 2 if I remember correctly. I was running under the assumption they were doing similar curriculum to my LA 1 class"]\',\n       \'[\'I still think that a class might be more useful. Mostly because the tests and assignments will force you to think about concepts in certain ways that you might not necessarily pick up from being self taught. But it is certainly better than not considering it at all\', \'This is a cope to rationalize not taking a hard class.\']\',\n       \'[\'Good luck man. You might discover you really enjoy it. Proofs in algebra can be much more elegant than in calculus/analysis (no bashing epsilon deltas with inequalities).\\n\\nIf you want to read ahead in advance get any reasonably formal book and start working with axioms of vector spaces immediately. The sooner you move past "vectors as arrows", which is the geometric picture you will get in HS or 3b1b videos, the better. This is fine for working in R2 and R3 or Rn like you usually do in calculus because they\\\'re inner product spaces equipped with the Euclidean norm. But you need to move beyond that quickly in linear algebra.\']\',\n       \'[\'Hate these basic ass wranglers.\', "I need to start dropping that into interviews randomly.\\n\\nMe: I don\'t mind spelunking around in the data to find what\'s useful.\\n\\nInterviewer: We actually don\'t use Splunk here.\\n\\nAnd then just give them the ol\' Leonardo Dicaprio in Inception stare."]\',\n       \'[\'Big assumption to believe a corporation has this level of discernment. But I do agree\']\',\n       \'[\'honestly true, imma take the class tho i underestimated how important it was\']\',\n       \'[\'[deleted]\']\'],\n      dtype=\'object\', length=4944)] are in the [columns]'